#!/bin/bash

pip-install-and-add-to-requirements () {
    pkg=$(echo $1 | tr "[:upper:]" "[:lower:]")
    pip install $pkg
    versioned=$(pip freeze | tr "[:upper:]" "[:lower:]" | grep $pkg==)
    echo $versioned >> requirements-dev.txt
}


usage="Creates a Django base project 

Usage: $(basename "$0") project-name 
Where:
    project-name    The project's name (duh!)"

if [ -z $1 ] || [  ]
then
    echo "$usage"
else

	#cria a pasta e o ambiente e ativa
	mkdir $1
	cd $1
	python -m venv .$1
	source .$1/bin/activate 
	
	#atualiza o pip, instala as libs e cria o requirements.txt
	touch requirements-dev.txt
	pip install --upgrade pip
	pip-install-and-add-to-requirements django
	pip-install-and-add-to-requirements python-decouple
	pip-install-and-add-to-requirements dj-database-url
	pip-install-and-add-to-requirements whitenoise
	pip-install-and-add-to-requirements django-extensions
	pip-install-and-add-to-requirements django-test-without-migrations

	cp requirements-dev.txt requirements.txt
	pip-install-and-add-to-requirements jupyter

	#cria .env file
	cp ../env-sample .env

	#cria o projeto django e a app core
	django-admin startproject $1 .
	python manage.py startapp core
	mv core $1 

	#cria README.md
	echo -e "# $1" > README.md
	echo -e "##Criando novo ambiente" >> README.md
	echo -e "Crie um virtualenv, ative e instale as dependências:" >> README.md
	echo -e "\`\`\`console\npython -m venv .$1\nsource .$1/bin/activate \npip install -r requirements-dev.txt \ncp contrib/env-sample .env\n\`\`\`" >> README.md
	echo -e "##Criando deploy Heroku" >> README.md
	echo -e "Crie uma instancia no heroku:" >> README.md
	echo -e "\`\`\`console\nheroku apps:create seu-projeto\nheroku config:set SECRET_KEY=\`python contrib\keygen.py\`\nheroku config:set DEBUG=False\nheroku config:set ALLOWED_HOSTS=.herokuapp.com\n\`\`\`" >> README.md

	#arquivos para iniciar projeto do git
	mkdir contrib
	cp ../keygen.py contrib/
	cp ../env-sample contrib/
	
	#prepara a configuração para o Heroku
	echo -e "gunicorn==20.0.4\npsycopg2==2.8.6" >> requirements.txt
	echo "web: gunicorn $1.wsgi --log-file - " > Procfile

	#config git
	git init .
	echo -e ".$1\n.env\n.idea\n*.sqlite3\n*pyc\n__pycache__\nstaticfiles" > .gitignore

	
fi
